---
- name: Set apt keys
  ansible.builtin.get_url:
    url: "{{ item.signed_by }}"
    dest: "{{ apt_keyrings_dir }}/{{ item.name }}.asc"
    mode: '0644'
  when:
    - item.signed_by is defined
    - item.signed_by != ''
    - item.signed_by is uri(schemes=['https'])

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: >-
      {{ type }}
      {% if (architecture is not none and architecture != '') or (signed_by is not none and signed_by != '') %}
      [{{ [architecture, signed_by] | reject('equalto', '') | reject('equalto', none) | list | join(' ') }}]
      {% endif %}
      {{ uri }} {{ codename }} {{ components }}
    filename: "{{ item.filename | default(item.name) }}"
    state: "{{ item.state | default('present') }}"
    update_cache_retries: "{{ apt_update_cache_retries | default(omit) }}"
    update_cache_retry_max_delay: "{{ apt_update_cache_retry_max_delay | default(omit) }}"
    update_cache: "{{ apt_update_cache | default(omit) }}"
    validate_certs: "{{ apt_validate_certs | default(omit) }}"
  vars:
    type: "{{ sub_item.type }}"
    architecture: >-
      {% if item.architectures | default([]) | length > 0 %}
      arch={{ item.architectures | join(',') }}
      {% endif %}
    signed_by: >-
      {% if item.signed_by | default('') != '' %}
      signed-by={{ apt_keyrings_dir }}/{{ item.name }}.asc
      {% endif %}
    uri: "{{ sub_item.uri }}"
    codename: "{{ sub_item.suite }}"
    components: "{{ item.components | default(['main']) | join(' ') }}"
  loop: >-
    {%- set resp = [] -%}
    {%- for type in item.types -%}
    {%- for uri in item.uris -%}
    {%- for suite in item.suites -%}
    {%- set _ = resp.append({
      'type': type,
      'uri': uri,
      'suite': suite
      }) -%}
    {%- endfor -%}
    {%- endfor -%}
    {%- endfor -%}
    {{ resp }}
  loop_control:
    loop_var: sub_item
