---

- name: Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(omit) }}"
  tags:
    - apt-update
    - apt-upgrade

- name: Upgrade all packages to their latest version  # noqa: package-latest
  ansible.builtin.apt:
    name: "*"
    state: latest
  tags:
    - apt-upgrade

- name: Upgrade
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_type }}"
    update_cache: true
  tags:
    - apt-upgrade

- name: Install packages conditionally
  ansible.builtin.apt:
    name: "{{ item.packages | default([]) }}"
    state: "{{ item.state | default('present') }}"
    purge: "{{ apt_remove_purge }}"
  when:
    - item.packages | default([]) | length > 0
    - item.condition | default(true)
  loop: "{{ apt_packages_conditional | default([]) }}"
  tags:
    - apt-remove

- name: Autoremove  # noqa args[module]
  ansible.builtin.apt:
    autoremove: true
  when: apt_autoremove | bool
  tags:
    - apt-autoremove
