---

- name: Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(omit) }}"
  tags:
    - apt-update
    - apt-upgrade

- name: Upgrade all packages to their latest version  # noqa: package-latest
  ansible.builtin.apt:
    name: "*"
    state: latest
  tags:
    - apt-upgrade

- name: Upgrade
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_type }}"
    update_cache: true
  tags:
    - apt-upgrade

- name: Install packages  (state=present is optional)
  ansible.builtin.apt:
    name: "{{ apt_packages | default([]) }}"
    state: present


- name: Remove
  ansible.builtin.apt:
    name: "{{ apt_packages_remove }}"
    state: absent
    purge: "{{ apt_remove_purge }}"
  tags:
    - apt-remove

- name: Autoremove  # noqa args[module]
  ansible.builtin.apt:
    autoremove: true
  when: apt_autoremove | bool
  tags:
    - apt-autoremove
