---
- name: Ensure apt-transport-https is installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
    state: present
    update_cache: true
  when:
    - apt_repositories is defined and apt_repositories | length > 0
    - (not apt_deb822) | bool
  tags:
    - apt-repo

- name: List files matching '*.list|*.sources'
  ansible.builtin.find:
    paths: "/etc/apt"
    patterns:
      - "*.list"
      - "*.sources"
    recurse: true
  register: to_remove
  when:
    - apt_repositories_remove | bool

- name: Remove apt repository files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: >-
    {{ to_remove.files | map(attribute='path') |
    reject('search', apt_repositories_host | map(attribute='name') | join('|')) |
    list }}
  loop_control:
    label: "{{ item }}"
  when:
    - apt_repositories_remove | bool
    - to_remove.matched > 0
  tags:
    - apt-repo
    - apt-repo-remove

- name: Configure apt repositories
  ansible.builtin.include_tasks: apt_repo_item.yml
  loop: "{{ apt_repositories }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - apt_repositories is defined and apt_repositories | length > 0
    - (not apt_deb822) | bool
  tags:
    - apt-repo

- name: Add apt deb822 repository
  ansible.builtin.deb822_repository:
    name: "{{ item.name | default('example') }}"
    types: "{{ item.types | default(['deb']) }}"
    architectures: "{{ item.architecture | default(omit) }}"
    components: "{{ item.components | default(['main']) }}"
    suites: "{{ item.suites | default(ansible_facts['distribution']) }}"
    uris: "{{ item.uris }}"
    signed_by: "{{ item.signed_by | default('') }}"
    state: "{{ item.state | default('present') }}"
    enabled: "{{ item.enabled | default(true) }}"
  loop: "{{ apt_repositories | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: apt_deb822 | bool
  tags:
    - apt-repo

- name: Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(omit) }}"
  tags:
    - apt-repo
    - apt-update
    - apt-upgrade
