---
- name: Backup existing repositories file
  ansible.builtin.copy:
    src: /etc/apk/repositories
    dest: /etc/apk/repositories.bak
    remote_src: true
    mode: "0644"
  when:
    - apk_repos_backup | bool
    - apk_repositories is defined and apk_repositories | length > 0
  tags:
    - repo

- name: Remove all repository entries
  ansible.builtin.copy:
    content: ""
    dest: /etc/apk/repositories
    mode: "0644"
  when:
    - apk_repos_remove | bool
    - apk_repositories is defined and apk_repositories | length > 0
  notify:
    - Update apk cache
  tags:
    - repo

- name: Configure apk repositories
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
    create: true
    mode: "0644"
  loop: "{{ apk_repositories | default([]) }}"
  loop_control:
    label: "{{ item.name | default(item.url) }}"
  when:
    - apk_repositories is defined and apk_repositories | length > 0
  notify:
    - Update apk cache
  tags:
    - repo
