---
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  gather_facts: true
  vars:
    apt_repositories_remove: false
    apt_repositories_host:
      - name: debian-security
        types: ['deb']
        uris:
          - "https://deb.debian.org/debian-security"
        suites: ["{{ ansible_facts['distribution_release'] }}-security"]
        components: ["main"]
  roles:
    - role: s4int.package_manager
